### ISSUE TITLE
Content page URL reverted back to /:slug when next release is out

### ISSUE THREAD

**Issue by Mopok** [lemonstand/lscloud-theme-meyer#132]
With next LS release we should change the content page's URL back to /:slug. I changed it in #131 because the bug was affecting URLs on this theme. When the fix is out we can change it back

**Comment by dhalarewich** [comment]
@jennbrewer can you investigate this one, and make the change suggested if it's needed or would be an improvement? I'm not sure what the content page URLs are right now, but I believe the suggestion here is intended to have cleaner content page URLs.

Changing it to /:slug may have some implications and need testing afterward.
