### ISSUE TITLE
Cart item columns not aligned

### ISSUE THREAD

**Issue by rpaul26** [lemonstand/lscloud-theme-meyer#199]
When multiple items are in the cart, the columns don't line up vertically for quantity and price. See screen capture below.

![image](https://cloud.githubusercontent.com/assets/9263021/25644934/95167ae0-2f5e-11e7-8f98-83826ec47391.png)

**Comment by Mopok** [comment]
@JHarden I think the prices are still a bit off the header of the column. See:

![screen shot 2017-05-25 at 3 58 21 pm](https://cloud.githubusercontent.com/assets/14959054/26473963/3208b514-4163-11e7-972f-86e14fa06bc1.png)

Maybe swapping the price with the (x) will help here.

**Comment by JHarden** [comment]
<img width="1070" alt="screen shot 2017-05-26 at 11 01 07 am" src="https://cloud.githubusercontent.com/assets/7881694/26507168/01ca3700-4204-11e7-98c6-d5bd48fef105.png">

@Mopok @rpaul26 Let me know what you think ^
Aligned items and increased the width of the page as per above screenshot: 
Pull Request #241

**Comment by Mopok** [comment]
@JHarden Could you move the quantity +/- under the QTY column? And the (X) in the middle of the +/- and price?

**Comment by dhalarewich** [comment]
@Mopok if this hasn't been completed, can you take over and get it done? Thanks

**Comment by dhalarewich** [comment]
@jennbrewer Can you review where this is at, and if already completed just close the issue, and if there's still some visual bugs (like quantity field not aligning to table column header), work on a fix?
