### ISSUE TITLE
Cart total, savings, total confusing when discounts applied

### ISSUE THREAD

**Issue by rpaul26** [lemonstand/lscloud-theme-meyer#200]
In the screen captures below, there are 3 discounts applied:

1 - Faded lemons shirt is set to "On sale" with a price of $15 (vs. original price of $18)

2. There is a discount rule applied for all cart items in the "Women's" category with a discount of 20% off (would apply to graphic lemons and faded lemons making the graphic lemons actual discounted price $17.60 and the faded lemons actual discounted price $12).

3. There is a discount rule applied for entering a coupon code of "promo" that discounts the entire cart by 10%.

The end total of $49.14 is correctly calculated but it's a bit of a confusing view, as it makes me think the end total should be the cart total minus the savings.

**Cart View**
![image](https://cloud.githubusercontent.com/assets/9263021/25645075/d39212b0-2f5f-11e7-8553-b63012c10e1f.png)

**Checkout View**
![image](https://cloud.githubusercontent.com/assets/9263021/25645113/196e5190-2f60-11e7-97dc-66680a9e4395.png)

I actually think the approach taken for the order detail from the order history is the easiest to understand, maybe we can just use this methodology across all?

![image](https://cloud.githubusercontent.com/assets/9263021/25645478/57893eec-2f63-11e7-8101-d2751f2675be.png)

**Comment by dhalarewich** [comment]
Merged
