### ISSUE TITLE
Receipt Page - misaligned columns and inconsistent totalling from cart/checkout

### ISSUE THREAD

**Issue by rpaul26** [lemonstand/lscloud-theme-meyer#204]
A slightly different layout and totalling methodology appears to have been used here than on the cart/checkout pages (more item level discounts shown from both "on sale" and discount rules applied to cart items). Columns for the items also don't line up.

![image](https://cloud.githubusercontent.com/assets/9263021/25645432/d346b5ce-2f62-11e7-924d-7f5da61e8df6.png)

**Comment by dhalarewich** [comment]
@jennbrewer let's make the design of this page consistent with the cart page in terms of logic to total items, and design.
