### ISSUE TITLE
Out of stock product behaviour on front-end unexpected

### ISSUE THREAD

**Issue by rpaul26** [lemonstand/lscloud-theme-meyer#213]
When inventory tracking is turned on for a specific product and the "hide when out of stock" is also checked, the product will still be displayed on the front end (category list, search results, etc.) when it is out of stock. Not sure if this is a theme related problem or if this is more backend.

Additionally, when inventory tracking is on and an item is out of stock but "hide when out of stock" is not checked and neither is "allow pre-order" attempts to add the product to the cart fail and the cart page loads and shows an empty cart. Seems like there should be some kind of warning that the item is out of stock and maybe the button for "add to cart" should be hidden/disabled in this situation.

**Comment by jason-sasquatchstudio** [comment]
This is two separate issues. I've made an issue for the second paragraph here: https://github.com/lemonstand/lscloud-theme-meyer/issues/281
From now on, this can track the issue of a product incorrectly showing up in lists while out of stock.
