### ISSUE TITLE
Inconsistent navigation links to About content - which is also hardcoded (but shouldn't be)

### ISSUE THREAD

**Issue by rpaul26** [lemonstand/lscloud-theme-meyer#215]
**Details**

The header-menu and footer-menu widget blocks each have a menu item ("Company" for header-menu "About Us" for footer-menu). 

The header menu appears to be a broken link that links to a non-existent CMS site page called "Company" (/content/company), which will be very confusing.

The footer menu item links to the "About Us" page template directly (/about-us) and the "Lorem ipsum..." content is hardcoded. This is very bad UX as the content isn't editable anywhere by nontechnical users. 

**Recommended Fix**

The theme would be much more usable if:

- We used the same label (ie. "About Us") in both the header and footer navigation menus.
- The "About Us" menu items linked to an easily editable CMS site page that applies the standard "Content" page template for Meyer. 

The only issue with this is that there isn't a default "About Us" CMS site page to apply the page template to currently built into LemonStand.

@dhalarewich - alternative is to use a widget block (there is one already, see below).

**Additional Related Issue**

There is a widget block labelled "about-page" that isn't being used by the "About Us" page template. We should remove this widget block from the theme if it isn't being used.

**Comment by jason-sasquatchstudio** [comment]
In this PR https://github.com/lemonstand/lscloud-theme-meyer/pull/264 in this commit https://github.com/lemonstand/lscloud-theme-meyer/pull/264/commits/61b136691929b9e6d1f9a16da92f4783768ff8b7 I fixed this issue. I used the widget block that already existed, made the page url be /about, and the link text be "About Us". I had to change the widget some to get it to display nicely.
