### ISSUE TITLE
Mailchimp integration theme options don't do anything

### ISSUE THREAD

**Issue by rpaul26** [lemonstand/lscloud-theme-meyer#217]
When entering a valid MailChimp API key and List ID for the theme settings and then entering a valid email address on the home page to sign up to the newsletter, nothing happens (no visual feedback and email is not added to the MailChimp list). There also appear to be 2 partials related to MailChimp with the same name in this theme ("partial-mailchimp"), but there should probably be just one.

**Comment by dhalarewich** [comment]
Looks like it was merged. Closing.
