### ISSUE TITLE
Theme setting - banner button style - does it do anything?

### ISSUE THREAD

**Issue by rpaul26** [lemonstand/lscloud-theme-meyer#219]
When changing this setting I couldn't figure out where the banner button I was supposed to be changing was. I didn't notice any button styles changing though.

**Comment by dhalarewich** [comment]
@jennbrewer can you look into this briefly and just remove the theme setting if you confirm it doesn't do anything?

**Comment by jennbrewer** [comment]
There's no button there, removed setting.

**Comment by jennbrewer** [comment]
Where is this located in the code? Not seeing this in `theme.yaml` or _theme manifest_
