### ISSUE TITLE
Theme settings - Google Maps coords - are they used somewhere?

### ISSUE THREAD

**Issue by rpaul26** [lemonstand/lscloud-theme-meyer#221]
There's a field for Google Maps Latitude and Longitute in the theme settings but I couldn't see where they're actually applied to a map. I thought originally it might be the contact page but there is no map on that page, just a form.

**Comment by dhalarewich** [comment]
@jennbrewer if they're not used anywhere (I couldn't find them either, but maybe a file search from your IDE would help) let's remove the theme settings.
