### ISSUE TITLE
Ad panel on home page - text alignment is off when longer text used

### ISSUE THREAD

**Issue by rpaul26** [lemonstand/lscloud-theme-meyer#223]
Center aligning text title and sub-title above the CTA button might be a better idea, as current alignment feels unbalanced to the right of the page. Screen capture to illustrate below:

![image](https://cloud.githubusercontent.com/assets/9263021/25651102/1a0f4222-2f96-11e7-9bce-486d449bf26d.png)

**Comment by Mopok** [comment]
@JHarden Missed something in the PR, but you removed something I added on purpose. The background colour was there because it was a fallback for no image being used in the background. Please add that back.

**Comment by JHarden** [comment]
@Mopok sorry about that, must have snipped it.
Pull Request: #242  adds it back in
