### ISSUE TITLE
Clean up incomplete 1 page checkout

### ISSUE THREAD

**Issue by dhalarewich** [lemonstand/lscloud-theme-meyer#244]
There was an attempt at including multiple checkout paths that would be selectable through a theme customization option. 

Since that work isn't complete, it should not remain in the code that's released to customers. 

Let's clean up remnants of the code meant for the 1 page checkout.

**Comment by aperdomo** [comment]
### Repro Steps
- Switch back and forth between between shipping method and pay step.
