### ISSUE TITLE
Meyer not displaying currency type from settings

### ISSUE THREAD

**Issue by robotpony** [lemonstand/lscloud-theme-meyer#258]
> I've confirmed that regardless of what the Store config currency and symbol are set to, Meyer only displays $ in most places (ie. home page, category listings, product page, cart items). It does show the correct currency in at least one place that I found (subtotal and totals for cart page, and the minicart view in the checkout pages). We should do a full audit of all pages where the currency symbol is displayed, including My Account, Receipt, Checkout, Cart, Product, Category, Home and anywhere else (even for shortcodes inserted into blog posts) to make sure that the currency symbol is correctly using the setting in store config.

Theme should display correct currency for the following cases (and any others found):

- product page/listings
- cart (all steps), including mini cart
- receipt page
- my account / order history pages

**Comment by jennbrewer** [comment]
Customer https://turveysfinefurniture.lemonstand.com/ trying to display £ 

https://app.intercom.io/a/apps/7236196445273cea007287c0c90a2f0d598567cc/respond/inbox/1503786/conversations/12380456204

**Comment by robotpony** [comment]
This should be fixed in master now, can you close once your testing confirms?

**Comment by rudy-sasquatchstudio** [comment]
Verified in our branch that this is working.  Changed our store version to the following _#!25.00.  Test can be confirmed here. https://meyer-staging.lemonstand.com/product/brushed-lemons-white
