### ISSUE TITLE
Editing any of the home-ribbon-one (or -two or -three) widget blocks causes server error

### ISSUE THREAD

**Issue by rpaul26** [lemonstand/lscloud-theme-meyer#260]
Using the WYSIWYG editor on any of the widget-blocks listed above causes a server error, even if just a minor text edit. 

Steps to reproduce:

Edit any of the following widget blocks in Meyer using the WYSIWYG editor (in normal or code view):

home-ribbon-one
home-ribbon-two
home-ribbon-three

Even making a small text change of 1-2 characters caused the error below:

![image](https://user-images.githubusercontent.com/9263021/30139489-0587c3ba-9323-11e7-8b5d-67e4fee85ede.png)

**Comment by dhalarewich** [comment]
Might be missing escaping somewhere.

**Comment by dhalarewich** [comment]
@rudy-sasquatchstudio could you please assign and work on this one as well?

**Comment by rudy-sasquatchstudio** [comment]
fixed - appears that blocks were using twig code.  Cannot use TWIG code inside of WYSIWYG editor otherwise it will complain
