### ISSUE TITLE
Sub-category URLs are broken

### ISSUE THREAD

**Issue by dhalarewich** [lemonstand/lscloud-theme-meyer#261]
Meyer is using $route wrong. It's just setting by parsing window.location rather than actually using $route.

We need to make the URLs for sub-categories use clean URLs like `/categories/office/desks` instead of `/categories/office?sub-category=desks` as they currently do.

The URLs should also change in the browser when clicking between them in the sidebar list.

![image](https://user-images.githubusercontent.com/1108337/30391422-1f3afd7c-986e-11e7-8aa6-faf7843ce1ab.png)

Linking to these category URLs directly should also work (ie load the correct products in the product grid to the right, along with the correct filters along the top).

**Comment by rudy-sasquatchstudio** [comment]
Fixed routing issues.  URL structure has been updated but not to the extend described.  While sticking with the functionality of angular the following URL structure has now been adopted... https://meyer-staging.lemonstand.com/products#/womens?category=yellow.

**Comment by jason-sasquatchstudio** [comment]
A more full example.

https://meyer-staging.lemonstand.com/products#/womens/yellow?search=fad&sale=false&price=18
