### ISSUE TITLE
Meyer value escaping needs improvement

### ISSUE THREAD

**Issue by dhalarewich** [lemonstand/lscloud-theme-meyer#262]
Any value that hits the Meyer JSON should be escaped so that valid JSON can be generated.

Also check other values (titles, descriptions, SEO tags, etc.)

First fix pass is here in this PR: #257 

> It fixes the initial error #256 , however, something else is causing a different error. This different error is not fatal from what I can noticed, so it is an improvement.

Goal is to get values escaped properly throughout the Meyer theme. Please close #256 when that's resolved as well.

**Comment by jason-sasquatchstudio** [comment]
In this PR https://github.com/lemonstand/lscloud-theme-meyer/pull/264 I went through all the api-<thing> pages and changed every "{{ <thing> }}" to {{ <thing> | json_encode() | raw }}. This uses Twig's json encoding ability to make sure it gets done right. It would be more future-proof to create the json objects as Twig objects and json encode the whole thing at once, but that would be a harder change to read, so I did it this way.
