### ISSUE TITLE
Regression: Price filter & category sort not working together on shop page

### ISSUE THREAD

**Issue by jennbrewer** [lemonstand/lscloud-theme-meyer#270]
Category filter not working on Product Page - breaks Price Filter.

## Context
Categories incorrect and not working on click. 

## Steps to Reproduce

[Product Page](https://meyer.lemonstand.com/products#/?sale=false&price=849.5)

Category filter not working:

<img width="1274" alt="screen shot 2017-10-30 at 1 51 47 pm" src="https://user-images.githubusercontent.com/6082087/32186803-812306c6-bd79-11e7-9edb-4683a214058b.png">

Then breaks the pricing filter:

<img width="331" alt="screen shot 2017-10-30 at 9 38 31 am" src="https://user-images.githubusercontent.com/6082087/32173692-2ff8607a-bd56-11e7-9f55-312a6879efb3.png">

**Comment by rudy-sasquatchstudio** [comment]
I can't seem to replicate.

Steps taken: 

1) Visit [products page ](https://meyer.lemonstand.com/categories/living-room) 
2) select pricing filter and change values. screen is properly filtering out based on price values.  

Am I missing something here?

**Comment by jennbrewer** [comment]
Steps to replicate:

1. Go to category "Office" (for example). 
2. Click a **category** (chairs (2), or desks (3)).
<img width="123" alt="screen shot 2017-11-01 at 2 56 22 pm" src="https://user-images.githubusercontent.com/6082087/32291927-d8f3f684-bf14-11e7-9650-dd12a0335b1e.png">
3. Then try the price filter.

**Comment by rudy-sasquatchstudio** [comment]
I honestly can't replicate this issue sorry.  

![image](https://user-images.githubusercontent.com/24289426/32470906-7d3ec95a-c30f-11e7-9502-d0b7fbcbd10c.png)

![image](https://user-images.githubusercontent.com/24289426/32470919-9078d5f6-c30f-11e7-905d-170d9935e34a.png)

![image](https://user-images.githubusercontent.com/24289426/32470933-9e73260c-c30f-11e7-903e-a4108eba0406.png)

![image](https://user-images.githubusercontent.com/24289426/32470942-aae12646-c30f-11e7-8fb0-c37823a6152d.png)

**Comment by rudy-sasquatchstudio** [comment]
@jennbrewer do you mind providing details maybe on your browser and the version it is using?  Maybe it is browser/version specific?
