### ISSUE TITLE
Should not be able to add to cart when product is out of stock.

### ISSUE THREAD

**Issue by jason-sasquatchstudio** [lemonstand/lscloud-theme-meyer#281]
I've split this issue out of the issue here: https://github.com/lemonstand/lscloud-theme-meyer/issues/213
It's separate from the other issue described there.

When inventory tracking is on and an item is out of stock but "hide when out of stock" is not checked and neither is "allow pre-order" attempts to add the product to the cart fail and the cart page loads and shows an empty cart. Seems like there should be some kind of warning that the item is out of stock and maybe the button for "add to cart" should be hidden/disabled in this situation.

**Comment by jennbrewer** [comment]
When out of stock and "hide when out of stock" is not checked, it shows:

<img width="519" alt="screen shot 2017-11-23 at 3 22 28 pm" src="https://user-images.githubusercontent.com/6082087/33187764-24e5cd48-d062-11e7-8229-38e3752c6230.png">
