### ISSUE TITLE
Test master branch

### ISSUE THREAD

**Issue by dhalarewich** [lemonstand/lscloud-theme-meyer#294]
Now that we merged in regression fixes, and visual fixes into Master, we need to re-test before deploying.

Download a zip of Master, and import this into your testing store as a **new** theme. Test the following in Safari, Chrome and FireFox:

- [x] All [regression issues](https://github.com/lemonstand/lscloud-theme-meyer/issues?q=is%3Aissue+is%3Aopen+label%3Aregression) have resolved and also #213 and #281

- [x] Verify all visual fixes that you recently closed are resolved in merged theme

- [x] Navigating categories and sub-categories, and pagination

- [x] Add product to cart which has product options and extras

- [x] Checking out, and viewing order history after

- [x] Logging into store using registered user account

**Comment by jennbrewer** [comment]
@dhalarewich All issues resolved except for #274 I still don't see this.
